version: '3'

services:

  repo-search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        bundle config set without 'test best_practices'
        bundle install --jobs 4
        bin/rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/repo-search/
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
    entrypoint: ./docker-entrypoint.sh
